name: Build and Deploy (Triggered by workflow_run)

on:
  workflow_run:
    workflows: ["Manual Release Tag"]
    types:
      - completed

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}  # Ensure we have the entire repo plus this tag

      - name: Fetch all tags # (optional if fetch-depth: 0 doesn't fetch tags)
        run: git fetch --tags

      - name: Capture Commit Metadata
        run: |
          echo "Commit: ${{ github.sha }}" > commit_info.txt
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "none")
          echo "Previous Tag: $PREV_TAG" >> commit_info.txt

      - name: Build Artifact
        run: |
          mkdir build
          cp index.html build/
          cp commit_info.txt build/
          # Disable Jekyll processing
          touch build/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
